services:
  primes-service:
    image: primes-service
    build:
      context: ../prime-service
      dockerfile: Dockerfile
    container_name: primes-service
    ports:
      - "4001:8080"
    restart: "no"
  
  primes-service-database-postgres:
    image: postgres:alpine
    container_name: primes-database
    ports:
      - "5001:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=primes 